### ISSUE TITLE
Core dumped when rendering

### ISSUE THREAD

**Issue by FYRichie** [mworchel/differentiable-shadow-mapping#3]
Hi there,
I'm rendering a mesh with a point light source. The camera I use is a `perspective` camera. The code is shown as follows:
```python
camera = Camera(
    projection_matrix=create_perspective_projection_matrix(fovy=math.atan(T_V_FOV), aspect=w / h, near=0.0, far=15.0, device=device),
    view_matrix=create_lookat_matrix(eye=[0.0, 0.0, 0.0], focus=[0.0, 0.0, 1.0], up=[0.0, 1.0, 0.0]).to(device),
)
scene_mesh = weld_seams(Mesh(scene_pc, scene_face))
l = PointLight(ls_pc[0])
renderer = SimpleRenderer(dr.RasterizeGLContext(device=device))
img = renderer.render([scene_mesh], lights=[l], camera=camera, resolution=(h, w))
print(img.shape)
```

However, the code stops with the following error:
<img width="423" alt="Screen Shot 2023-11-16 at 6 20 12 AM" src="https://github.com/mworchel/differentiable-shadow-mapping/assets/59409544/4046d069-e589-4641-a041-44b88f0bd815">

Is there any possible reasons that may lead to this error?
Thank you.

**Comment by FYRichie** [comment]
It seems that the error occurs when creating the renderer, but I have no idea how this error happens.

**Comment by mworchel** [comment]
Hi,

it looks like an error from within `nvdiffrast` (AFAIK the GLContext uses egl). Could you try using `dr.RasterizeCudaContext` instead of `dr.RasterizeGLContext`?

**Comment by FYRichie** [comment]
Thanks a lot! It solves the problem. Should I create a pull request to update the documentation?

**Comment by mworchel** [comment]
Awesome! This is more an issue of nvdiffrast but I will consider adding it to common issues.
